# Generated by Django 3.2.8 on 2021-10-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
    ]
