# Generated by Django 3.2.8 on 2021-10-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=140)),
                ('descripcion', models.TextField()),
                ('caracteristicas', models.CharField(max_length=140)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='productos.categoria')),
            ],
        ),
    ]
