# Generated by Django 3.2.8 on 2021-10-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'productos'},
        ),
        migrations.AlterField(
            model_name='productos',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
