# Generated by Django 3.2.8 on 2021-10-19 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20211018_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='producto',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Productos_Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioinsumo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioespecial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_precios', to='productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_fotos', to='productos.productos')),
            ],
        ),
    ]
