# Generated by Django 3.2.8 on 2021-10-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20211019_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos_fotos',
            options={'verbose_name_plural': 'productos_fotos'},
        ),
        migrations.AlterModelOptions(
            name='productos_precio',
            options={'verbose_name_plural': 'productos_precios'},
        ),
        migrations.AlterField(
            model_name='productos_fotos',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fotos'),
        ),
        migrations.AlterField(
            model_name='productos_fotos',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fotos'),
        ),
        migrations.AlterField(
            model_name='productos_fotos',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fotos'),
        ),
        migrations.AlterField(
            model_name='productos_fotos',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fotos'),
        ),
    ]
