# Generated by Django 3.2.8 on 2021-10-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_categoria_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('ruc', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('N', 'NACIONAL'), ('E', 'EXTRANJERO')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ManyToManyField(to='productos.Proveedor'),
        ),
    ]
