# Generated by Django 3.2.8 on 2021-10-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20211020_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id'], 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['id'], 'verbose_name_plural': 'proveedores'},
        ),
    ]
